// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsrdqothzeocycejcuwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcmRxb3RoemVvY3ljZWpjdXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzcxMDEsImV4cCI6MjA3MDg1MzEwMX0.whbdlKVWTwuFQ5SjPOMWfond-mi261DkbtqYnAcVMLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});